apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
{{- if not .Values.settings.serverAddr }}
{{ include "bblfshd-sidecar.volumes" . | indent 6 }}
{{- end }}
      containers:
{{- if not .Values.settings.serverAddr }}
{{ include "bblfshd-sidecar.containers" . | indent 6 }}
{{- end }}
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ required "missing image.tag" .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -bblfsh-addr={{ default "localhost:9432" .Values.settings.serverAddr }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
